# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Jonathan Campbell
email: campbell.jonathanc@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  My Thoughts on Software Development and Management
baseurl: "/bell" # the subpath of your site, e.g. /blog
url: "https://jon.camp" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: healsdata
permalink: /:year/:month/:title
analytics: UA-143768420-2
destination: bell/

# Author Settings
author: Jonathan Campbell
author-img: jcampbell.jpg # add your photo
social-twitter: healsdata
social-email: campbell.jonathanc@gmail.com
social-github: healsdata
social-linkedin: jon-camp


# Build settings
markdown: kramdown
#theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 5
paginate_path: "/page/:num"

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
